# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171021_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.FloatField()),
                ('balance', models.FloatField()),
                ('available', models.FloatField()),
            ],
        ),
    ]
